name: Build and Publish Docker Image

on:
  release:
    types: [published]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build . --tag ghcr.io/${{ github.repository_owner }}/my-app:latest

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/my-app:latest
